---
options:
  python-version:
    type: int
    default: 3
    description: THIS OPTION IS DEPRECATED AND HAS NO EFFECT
  triliovault-pkg-source:
    type: string
    default: "deb [trusted=yes] https://apt.fury.io/triliodata-4-0/ /"
    description: Repository address of triliovault packages
  backup-target-type:
    type: string
    default: nfs
    description: backup target type - nfs or s3
  nfs-shares:
    type: string
    default:
    description: NFS Shares mount source path
  nfs-options:
    type: string
    default: nolock,soft,timeo=180,intr,lookupcache=none
    description: NFS Options
  # DROP
  tv-data-dir:
    type: string
    default: /var/triliovault-mounts
    description: TrilioVault data mount point
  tv-data-dir-old:
    type: string
    default: /var/triliovault
    description: Old TrilioVault data dir
  # UNSUPPORTED
  tv-s3-secret-key:
    type: string
    default:
    description: S3 secret access key
  tv-s3-access-key:
    type: string
    default:
    description: S3 access key
  tv-s3-region-name:
    type: string
    default:
    description: S3 region name
  tv-s3-bucket:
    type: string
    default:
    description: S3 bucket name
  tv-s3-endpoint-url:
    type: string
    default:
    description: S3 endpoint URL
  tv-s3-ssl-cert:
    type: string
    default:
    description: |
      SSL CA to use when connecting to S3
  # General configuration
  tv-datamover-max-uploads-pending:
    type: int
    default: 3
    description: max_uploads_pending parameter value in /etc/tvault-contego/tvault-contego.conf
  tv-datamover-max-commit-pending:
    type: int
    default: 3
    description: max_commit_pending parameter value in /etc/tvault-contego/tvault-contego.conf
  tv-datamover-qemu-agent-ping-timeout:
    type: int
    default: 600
    description: qemu_agent_ping_timeout parameter value in /etc/tvault-contego/tvault-contego.conf
  cinder-http-retries:
    type: int
    default: 10
    description: |
      This is the number of times datamover will try to connect to
      the cinder service.
      This option is ignored if Trilio is before 4.1.94
